name: FaunaBTL
favicon: null
layout_spectrum: 0.5796455813106149
typography_spectrum: 0.9910888199228793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2166268234141171
  lightness: 0.8189318049699068
  saturation: 0.2584081038367003
  rhythmicContrast: 0.31420127348974347
purpose: []
